import { PokemonAbilityTypes, abilities } from "@/types/pokemon.type";
import { VariantProps, cva } from "class-variance-authority";

const chipVariants = cva(
    [
        "text-sm border",
        "rounded-full",
        "px-2.5",
        "py-0.5",
        "min-w-14",
        "text-center",
        "hover:opacity-70",
        "transition-opacity",
    ],
    {
        variants: {
            intent: {
                primary: "bg-blue-500 border-blue-500 text-white",
                secondary: "bg-gray-500 border-gray-500 text-white",
                danger: "bg-red-500 border-red-500 text-white",
                warning: "bg-yellow-500 border-yellow-500 text-white",
                info: "bg-violet-500 border-violet-500 text-white",
                success: "bg-green-500 border-green-500 text-white",
                default: "bg-yellow-500 border-yellow-500 text-white",
                "air-lock": "bg-blue-100 border-blue-100 text-blue-900",
                "arena-trap": "bg-brown-200 border-brown-200 text-brown-900",
                "battle-armor": "bg-gray-300 border-gray-300 text-gray-900",
                blaze: "bg-red-500 border-red-500 text-red-9000",
                cacophony: "bg-purple-200 border-purple-200 text-purple-900",
                chlorophyll: "bg-green-300 border-green-300 text-green-900",
                "clear-body": "bg-blue-300 border-blue-300 text-blue-900",
                "cloud-nine": "bg-blue-200 border-blue-200 text-blue-900",
                "color-change": "bg-pink-200 border-pink-200 text-pink-900",
                "compound-eyes": "bg-yellow-300 border-yellow-300 text-yellow-900",
                "cute-charm": "bg-pink-300 border-pink-300 text-pink-900",
                damp: "bg-blue-400 border-blue-400 text-blue-900",
                drizzle: "bg-blue-500 border-blue-500 text-blue-900",
                drought: "bg-orange-500 border-orange-500 text-orange-900",
                "early-bird": "bg-yellow-4000 border-yellow-400 text-yellow-900",
                "effect-spore": "bg-green-400 border-green-400 text-green-900",
                "flame-body": "bg-red-300 border-red-300 text-red-900",
                "flash-fire": "bg-red-400 border-red-400 text-red-900",
                forecast: "bg-blue-200 border-blue-200 text-blue-900",
                guts: "bg-red-600 border-red-600 text-red-900",
                "huge-power": "bg-yellow-500 border-yellow-500 text-yellow-900",
                hustle: "bg-red-700 border-red-700 text-red-900",
                "hyper-cutter": "bg-green-500 border-green-500 text-green-900",
                illuminate: "bg-yellow-600 border-yellow-600 text-yellow-900",
                immunity: "bg-green-600 border-green-600 text-green-900",
                "inner-focus": "bg-blue-600 border-blue-600 text-white",
                insomnia: "bg-purple-500 border-purple-500 text-purple-900",
                intimidate: "bg-red-800 border-red-800 text-white",
                "keen-eye": "bg-blue-700 border-blue-700 text-blue-900",
                levitate: "bg-purple-600 border-purple-600 text-purple-900",
                "lightning-rod": "bg-yellow-700 border-yellow-700 text-yellow-900",
                limber: "bg-blue-800 border-blue-800 text-white",
                "liquid-ooze": "bg-green-700 border-green-700 text-white",
                "magma-armor": "bg-red-900 border-red-900 text-white",
                "magnet-pull": "bg-gray-700 border-gray-700 text-white",
                "marvel-scale": "bg-blue-900 border-blue-900 text-white",
                minus: "bg-gray-800 border-gray-800 text-white",
                "natural-cure": "bg-green-800 border-green-800 text-white",
                oblivious: "bg-gray-900 border-gray-900 text-white",
                overgrow: "bg-green-900 border-green-900 text-white",
                "own-tempo": "bg-blue-900 border-blue-900 text-white",
                pickup: "bg-gray-900 border-gray-900 text-white",
                plus: "bg-yellow-800 border-yellow-800 text-white",
                "poison-point": "bg-green-900 border-green-900 text-white",
                pressure: "bg-gray-900 border-gray-900 text-white",
                "pure-power": "bg-blue-900 border-blue-900 text-white",
                "rain-dish": "bg-blue-900 border-blue-900 text-white",
                "rock-head": "bg-yellow-900 border-brown-900 text-white",
                "rough-skin": "bg-blue-900 border-blue-900 text-white",
                "run-away": "bg-blue-900 border-blue-900 text-white",
                "sand-stream": "bg-yellow-900 border-yellow-900 text-white",
                "sand-veil": "bg-yellow-900 border-yellow-9000 text-white",
                "serene-grace": "bg-blue-900 border-blue-900 text-white",
                "shadow-tag": "bg-gray-900 border-gray-900 text-white",
                "shed-skin": "bg-gray-900 border-gray-900 text-white",
                "shell-armor": "bg-blue-900 border-blue-900 text-white",
                "shield-dust": "bg-gray-900 border-gray-900 text-white",
                soundproof: "bg-gray-9000 border-gray-900 text-white",
                "speed-boost": "bg-blue-900 border-blue-900 text-white",
                static: "bg-blue-900 border-blue-900 text-white",
                stench: "bg-gray-900 border-gray-900 text-white",
                "sticky-hold": "bg-blue-900 border-blue-900 text-white",
                sturdy: "bg-blue-900 border-blue-900 text-white",
                "suction-cups": "bg-gray-9000 border-gray-900 text-white",
                swarm: "bg-yellow-900 border-yellow-900 text-white",
                "swift-swim": "bg-blue-900 border-blue-900 text-white",
                synchronize: "bg-blue-900 border-blue-900 text-white",
                "thick-fat": "bg-blue-900 border-blue-900 text-white",
                torrent: "bg-blue-900 border-blue-900 text-white",
                trace: "bg-blue-900 border-blue-900 text-white",
                truant: "bg-blue-900 border-blue-900 text-white",
                "vital-spirit": "bg-blue-900 border-blue-900 text-white",
                "volt-absorb": "bg-blue-900 border-blue-900 text-white",
                "water-absorb": "bg-blue-900 border-blue-900 text-white",
                "water-veil": "bg-blue-900 border-blue-900 text-white",
                "white-smoke": "bg-gray-900 border-gray-900 text-white",
                "wonder-guard": "bg-blue-900 border-blue-900 text-white",
                adaptability: "bg-green-700 border-green-700 text-white",
                aftermath: "bg-red-300 border-red-400 text-red-500",
                "anger-point": "bg-red-400 border-red-500 text-red-600",
                anticipation: "bg-red-500 border-red-600 text-red-700",
                "bad-dreams": "bg-red-600 border-red-700 text-red-800",
                download: "bg-red-700 border-red-800 text-red-900",
                "dry-skin": "bg-red-800 border-red-900 text-red-100",
                filter: "bg-red-900 border-red-100 text-red-200",
                "flower-gift": "bg-red-100 border-red-200 text-red-300",
                forewarn: "bg-red-200 border-red-300 text-red-400",
                frisk: "bg-red-300 border-red-400 text-red-500",
                gluttony: "bg-red-400 border-red-500 text-red-600",
                heatproof: "bg-red-500 border-red-600 text-red-700",
                "honey-gather": "bg-red-600 border-red-700 text-red-800",
                hydration: "bg-red-700 border-red-800 text-red-900",
                "ice-body": "bg-red-800 border-red-900 text-red-100",
                "iron-fist": "bg-red-900 border-red-100 text-red-200",
                klutz: "bg-red-100 border-red-200 text-red-300",
                "leaf-guard": "bg-red-200 border-red-300 text-red-400",
                "magic-guard": "bg-red-300 border-red-400 text-red-500",
                "mold-breaker": "bg-red-400 border-red-500 text-red-600",
                "motor-drive": "bg-red-500 border-red-600 text-red-700",
                multitype: "bg-red-600 border-red-700 text-red-800",
                "no-guard": "bg-red-700 border-red-800 text-red-900",
                normalize: "bg-red-800 border-red-900 text-red-100",
                "poison-heal": "bg-red-900 border-red-100 text-red-200",
                "quick-feet": "bg-red-100 border-red-200 text-red-300",
                reckless: "bg-red-200 border-red-300 text-red-400",
                rivalry: "bg-red-300 border-red-400 text-red-500",
                scrappy: "bg-red-400 border-red-500 text-red-600",
                simple: "bg-red-500 border-red-600 text-red-700",
                "skill-link": "bg-red-600 border-red-700 text-red-800",
                "slow-start": "bg-red-700 border-red-800 text-red-900",
                sniper: "bg-red-800 border-red-900 text-red-100",
                "snow-cloak": "bg-red-900 border-red-100 text-red-200",
                "snow-warning": "bg-red-100 border-red-200 text-red-300",
                "solar-power": "bg-red-200 border-red-300 text-red-400",
                "solid-rock": "bg-red-300 border-red-400 text-red-500",
                stall: "bg-red-400 border-red-500 text-red-600",
                steadfast: "bg-red-500 border-red-600 text-red-700",
                "storm-drain": "bg-red-600 border-red-700 text-red-800",
                "super-luck": "bg-red-700 border-red-800 text-red-900",
                "tangled-feet": "bg-red-800 border-red-900 text-red-100",
                technician: "bg-red-900 border-red-100 text-red-200",
                "tinted-lens": "bg-red-100 border-red-200 text-red-300",
                unaware: "bg-red-200 border-red-300 text-red-400",
                unburden: "bg-red-300 border-red-400 text-red-500",
            },
        },
        defaultVariants: {
            intent: "default",
        },
    }
);

type ChipVariantsType = VariantProps<typeof chipVariants>;

type ChipProps = {
    label: string;
    intent?: PokemonAbilityTypes;
} & ChipVariantsType;

// Define the isValidIntent function
function isValidIntent(intent: string): intent is PokemonAbilityTypes {
    return abilities.includes(intent as PokemonAbilityTypes);
}

function AbilitiesChip({ intent = "default", label }: ChipProps) {
    return (
        <div className={chipVariants({ intent: isValidIntent(intent) ? intent : "default" })}>
            {label}
        </div>
    );
}

export default AbilitiesChip;
