import { cva, VariantProps } from "class-variance-authority";

const chipVariants = cva(
    [
        "text-sm border",
        "rounded-full",
        "px-2.5",
        "py-0.5",
        "min-w-14",
        "text-center",
        "hover:opacity-70",
        "transition-opacity",
    ],
    {
        variants: {
            intent: {
                primary: "bg-blue-500 border-blue-500 text-white",
                secondary: "bg-gray-500 border-gray-500 text-white",
                danger: "bg-red-500 border-red-500 text-white",
                warning: "bg-yellow-500 border-yellow-500 text-white",
                info: "bg-violet-500 border-violet-500 text-white",
                success: "bg-green-500 border-green-500 text-white",
                default: "bg-white border-black text-black",
                airLock: "bg-blue-100 border-blue-100 text-blue-900",
                arenaTrap: "bg-brown-200 border-brown-200 text-brown-900",
                battleArmor: "bg-gray-300 border-gray-300 text-gray-900",
                blaze: "bg-red-500 border-red-500 text-red-900",
                cacophony: "bg-purple-200 border-purple-200 text-purple-900",
                chlorophyll: "bg-green-300 border-green-300 text-green-900",
                clearBody: "bg-blue-300 border-blue-300 text-blue-900",
                cloudNine: "bg-blue-200 border-blue-200 text-blue-900",
                colorChange: "bg-pink-200 border-pink-200 text-pink-900",
                compoundEyes: "bg-yellow-300 border-yellow-300 text-yellow-900",
                cuteCharm: "bg-pink-300 border-pink-300 text-pink-900",
                damp: "bg-blue-400 border-blue-400 text-blue-900",
                drizzle: "bg-blue-500 border-blue-500 text-blue-900",
                drought: "bg-orange-500 border-orange-500 text-orange-900",
                earlyBird: "bg-yellow-400 border-yellow-400 text-yellow-900",
                effectSpore: "bg-green-400 border-green-400 text-green-900",
                flameBody: "bg-red-300 border-red-300 text-red-900",
                flashFire: "bg-red-400 border-red-400 text-red-900",
                forecast: "bg-blue-200 border-blue-200 text-blue-900",
                guts: "bg-red-600 border-red-600 text-red-900",
                hugePower: "bg-yellow-500 border-yellow-500 text-yellow-900",
                hustle: "bg-red-700 border-red-700 text-red-900",
                hyperCutter: "bg-green-500 border-green-500 text-green-900",
                illuminate: "bg-yellow-600 border-yellow-600 text-yellow-900",
                immunity: "bg-green-600 border-green-600 text-green-900",
                innerFocus: "bg-blue-600 border-blue-600 text-white",
                insomnia: "bg-purple-500 border-purple-500 text-purple-900",
                intimidate: "bg-red-800 border-red-800 text-white",
                keenEye: "bg-blue-700 border-blue-700 text-blue-900",
                levitate: "bg-purple-600 border-purple-600 text-purple-900",
                lightningRod: "bg-yellow-700 border-yellow-700 text-yellow-900",
                limber: "bg-blue-800 border-blue-800 text-white",
                liquidOoze: "bg-green-700 border-green-700 text-white",
                magmaArmor: "bg-red-900 border-red-900 text-white",
                magnetPull: "bg-gray-700 border-gray-700 text-white",
                marvelScale: "bg-blue-900 border-blue-900 text-white",
                minus: "bg-gray-800 border-gray-800 text-white",
                naturalCure: "bg-green-800 border-green-800 text-white",
                oblivious: "bg-gray-900 border-gray-900 text-white",
                overgrow: "bg-green-900 border-green-900 text-white",
                ownTempo: "bg-blue-900 border-blue-900 text-white",
                pickup: "bg-gray-900 border-gray-900 text-white",
                plus: "bg-yellow-800 border-yellow-800 text-white",
                poisonPoint: "bg-green-900 border-green-900 text-white",
                pressure: "bg-gray-900 border-gray-900 text-white",
                purePower: "bg-blue-900 border-blue-900 text-white",
                rainDish: "bg-blue-900 border-blue-900 text-white",
                rockHead: "bg-yellow-900 border-brown-900 text-white",
                roughSkin: "bg-blue-900 border-blue-900 text-white",
                runAway: "bg-blue-900 border-blue-900 text-white",
                sandStream: "bg-yellow-900 border-yellow-900 text-white",
                sandVeil: "bg-yellow-900 border-yellow-900 text-white",
                sereneGrace: "bg-blue-900 border-blue-900 text-white",
                shadowTag: "bg-gray-900 border-gray-900 text-white",
                shedSkin: "bg-gray-900 border-gray-900 text-white",
                shellArmor: "bg-blue-900 border-blue-900 text-white",
                shieldDust: "bg-gray-900 border-gray-900 text-white",
                soundproof: "bg-gray-900 border-gray-900 text-white",
                speedBoost: "bg-blue-900 border-blue-900 text-white",
                static: "bg-blue-900 border-blue-900 text-white",
                stench: "bg-gray-900 border-gray-9000 text-white",
                stickyHold: "bg-blue-900 border-blue-900 text-white",
                sturdy: "bg-blue-900 border-blue-900 text-white",
                suctionCups: "bg-gray-9000 border-gray-900 text-white",
                swarm: "bg-yellow-900 border-yellow-900 text-white",
                swiftSwim: "bg-blue-900 border-blue-900 text-white",
                synchronize: "bg-blue-900 border-blue-900 text-white",
                thickFat: "bg-blue-900 border-blue-900 text-white",
                torrent: "bg-blue-900 border-blue-900 text-white",
                trace: "bg-blue-900 border-blue-900 text-white",
                truant: "bg-blue-900 border-blue-900 text-white",
                vitalSpirit: "bg-blue-900 border-blue-900 text-white",
                voltAbsorb: "bg-blue-900 border-blue-900 text-white",
                waterAbsorb: "bg-blue-900 border-blue-900 text-white",
                waterVeil: "bg-blue-900 border-blue-900 text-white",
                whiteSmoke: "bg-gray-900 border-gray-900 text-white",
                wonderGuard: "bg-blue-900 border-blue-900 text-white",
                "solar-power": "bg-red-800 border-red-800 text-white",
            },
        },
        defaultVariants: {
            intent: "default",
        },
    }
);

type ChipVariantsType = VariantProps<typeof chipVariants>;

type ChipProps = {
    label: string;
    intent?: string;
} & ChipVariantsType;

function AbilitiesChip({ intent = "default", label }: ChipProps) {
    return <div className={chipVariants({ intent })}>{label}</div>;
}

export default AbilitiesChip;
